@startuml
left to right direction

actor Usuario
actor Administrador

usecase "Login" as UC_Login
usecase "Registro" as UC_Register
usecase "Cerrar Sesión" as UC_Logout
usecase "Añadir Actividad" as UC_AddActivity
usecase "Ver Calendario" as UC_ViewCalendar
usecase "Ver Tareas Actuales" as UC_ViewCurrentTasks
usecase "Gestionar Usuarios" as UC_ManageUsers

Usuario --> UC_Login
Usuario --> UC_Register
Usuario --> UC_Logout
Usuario --> UC_ViewCalendar
Usuario --> UC_ViewCurrentTasks
Administrador --> UC_AddActivity
Administrador --> UC_ManageUsers

@enduml
